version: "3.8"

services:
  backend:
    build: ./backend
    container_name: job-tracker-backend
    ports:
      - "8004:8004"
    volumes:
      - ./backend/tracker.db:/app/tracker.db
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: job-tracker-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
